Vagrant.configure("2") do |config|

  config.vm.box = "CentOS_6_4_64"

  config.vm.network :private_network, ip: "192.168.33.40"
	config.vm.hostname = "wp.dev"
  config.ssh.forward_agent = true

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
  # Don't boot with headless mode
  #   vb.gui = true
  #
  # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.memory = 2048# 追記
      vb.cpus = 2         # 追記
  # IPv6とDNSでのネットワーク遅延対策で追記
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  if Vagrant.has_plugin?("vagrant-hostsupdater")
    config.hostsupdater.remove_on_suspend = true
  end

  #############################################################
  # Ansible provisioning (you need to have ansible installed)
  #############################################################


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventories/dev"
    ansible.limit = 'all'
  end

  config.vm.synced_folder "./", "/vagrant", type: "nfs"
  config.vm.synced_folder "./html/", "/var/www/html", type: "nfs"
end
