---
- name: Install System Packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - wget

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items: sys_packages #packages.ymlにリストを記載

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: SELinux Disable
  command: setenforce 0
  ignore_errors: True

- name: Edit selinux config
  command: sed -i -e "s/^SELINUX=enforing/SELINUX=disabled/g" /etc/selinux/config

- name: Stop iptables
  sudo: yes
  service: name=iptables state=stopped